### ISSUE TITLE
MIT Licensing Terms

### ISSUE THREAD

**Issue by embetrix** [roslynos/meta-stm32mp15x#1]
@bytewizer please check again the MIT License Terms 

`A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.`

**Comment by bytewizer** [comment]
@embetrix I have updated the project to included your exact license file and made sure to include any references you included in your header files back to the original project.   I have also included a link back to the original project.   I really appreciate your work on this project.   This is a really clean set of clean well written recipes.  Please don't hesitate to let me know if I'm missing anything.  Thanks again for your work on this project.

**Comment by embetrix** [comment]
@bytewizer okay great thanks
